;
; TEC-1F TEST ROM
; CRAIG JONES 2023
;
;
; TEC-1 I/O ASSIGNMENTS
;
KEYBUF	.EQU	00H	;MM74C923N KEYBOARD ENCODER
SCAN	.EQU	01H	;DISPLAY SCAN LATCH
DISPLY	.EQU	02H	;DISPLAY LATCH
PORT3	.EQU	03H	;ST3 (8X8), STROBE (RELAY BOARD) DATLATCH (DAT BOARD)
PORT4	.EQU	04H	;ST4 (8X8), LCD 'E' (DAT BOARD)
PORT5	.EQU	05H
PORT6	.EQU	06H
PORT7	.EQU	07H	;ENABLE/DISABLE SINGLE STEPPER (IF INSTALLED)

;----------------------------
; TOGGLE THE SPEAKER AND LED
;----------------------------
; MAKES AN AUDIBLE TONE AT 4MHZ 
; AND A CLICK, CLICK, USING THE RC OSCILLATOR 
;
;  RESTART 00H - RST 0
;WHEN POWER IS APPLIED TO THE TEC-1F
;THE Z80 STARTS EXECUTING INSTRUCTIONS FROM HERE
;
	.ORG	0000H
START	DI	; LET'S DISABLE INTERRUPTS
	XOR	A	;CLEAR A
AGAIN	XOR	B	;RESET COUNTER
LOOP	OUT	(SCAN),A
	DJNZ LOOP
	XOR	%10000000	;FLIP B7
	JP	AGAIN	;GO AGAIN

;
; RESTART 38H - RST 7  INTERRUPT
; IF INTERRUPTS ARE ENABLED,AND AN INT OCCURS- FURTHER INTERRUPTS
; ARE DISABLED, THE PROGRAM COUNTER IS PUSHED ONTO THE STACK, AND EXECUTION
; STARTS HERE
;
	.ORG	0038H
	JP	START       ; NO RAM FOR THE STACK, BESIDES INTERRUPTS ARE DISABLED
;
; RESTART 66H NMI VECTOR
; SAME AS ABOVE BUT NMI CANNOT BE DISABLED.
;
	.ORG	0066H
; THE TEC-1F HAS NMI CONNECTED TO THE INVERTED 74C923 KEYBOARD ENCODER DA 
; (DATA AVAILABLE) OUTPUT SO LETS DO A HALT 
    HALT
	.END


